### ISSUE TITLE
Instructions to install SeparableConvolution

### ISSUE THREAD

**Issue by saisk8** [sunxm2357/TwoStreamVAN#3]
Can you please provide instructions to install the SeperableConvolutions?

**Comment by sunxm2357** [comment]
Hi, sorry for the late reply. Could you check https://github.com/sunxm2357/TAI_video_frame_inpainting README file for the instruction on installing SeparableConvolution? It should be the same

**Comment by saisk8** [comment]
Hi, thanks for the reply. Although the compilation was successful, I still couldn't run the training script in `outer_prod_motion_mask`. I get import errors.

```
Traceback (most recent call last):
  File "train.py", line 13, in <module>
    from outer_prod_motion_mask.twostreamvan_environ import TwoStreamVAN
  File "../outer_prod_motion_mask/twostreamvan_environ.py", line 9, in <module>
    from outer_prod_motion_mask.twostreamvan_generator import *
  File "../outer_prod_motion_mask/twostreamvan_generator.py", line 5, in <module>
    from separable_convolution.SeparableConvolution import SeparableConvolution
  File "../separable_convolution/SeparableConvolution.py", line 1, in <module>
    import separable_convolution._ext.cunnex
  File "../separable_convolution/_ext/cunnex/__init__.py", line 3, in <module>
    from ._cunnex import lib as _lib, ffi as _ffi
ImportError: ../separable_convolution/_ext/cunnex/_cunnex.so: undefined symbol: __cudaRegisterFatBinaryEnd
```

Do you have any suggestions about how I should move forward with this?

**Comment by saisk8** [comment]
Can I know the CUDA version and PyTorch version you used to develop the code? I think that might solve the issue.
